version: 0.0
os: linux

files: 
  - source: /
    destination: /var/www/my-page

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: admin

    - location: scripts/retrieve_envs.sh
      timeout: 300
      runas: admin

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: admin

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: admin